openapi: 3.0.0
servers:
  - description: StorageLeaf API
    url: https://localhost/
info:
  description: The StorageLeaf API
  version: "2.7.0"
  title: StorageLeaf API

paths:
  /version:
    get:
      summary: Gets information about the server version
      operationId: version
      responses:
        '200':
          description: The server version information
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Version'
  /devices:
    get:
      summary: Gets all devices
      operationId: devices
      responses:
        '200':
          description: All available devices
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Device'
  /device/{deviceName}:
    get:
      summary: Gets a specific device
      operationId: device
      parameters:
        - in: path
          name: deviceName
          description: The device name
          required: true
          schema:
            type: string
      responses:
        '200':
          description: The device
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Device'

components:
  schemas:
    Version:
      type: object
      required:
        - code
        - name
        - date
      properties:
        code:
          type: integer
          example: 1
        name:
          type: string
          example: "v1.0.0"
        date:
          type: string
          format: date
          example: "30.05.19"

    Device:
      type: object
      required:
        - ID
        - name
      properties:
        ID:
          type: integer
          example: 1
        Projectname:
          type: string
          example: "My Device"

    SuccessResponse:
      required:
        - success
      properties:
        success:
          type: boolean
    ErrorResponse:
      required:
        - success
        - msg
      properties:
        success:
          type: boolean
        msg:
          type: string